export const TABLE_CLEAR_ROW = { "background-color": "transparent" };

/**
 * Table layout presets — structural differences, not just color swaps.
 * `colorMode`:
 *   - "none"    → section color only tints text/borders lightly (plain layouts)
 *   - "accent"  → section color fills header/footer
 */
export const TABLE_STYLE_TEMPLATES = [
  {
    id: "plain",
    label: "Plain",
    colorMode: "none",
    table: { width: "100%", "border-collapse": "collapse", "font-size": "10px", border: "none" },
    thead: { "background-color": "transparent", color: "#111111" },
    tfoot: { "background-color": "transparent", color: "#111111" },
    th: { padding: "6px 8px", "font-weight": "700", "font-size": "9px", "text-align": "left", border: "none", color: "#111111", "background-color": "transparent" },
    td: { padding: "6px 8px", border: "none", "background-color": "transparent", color: "#111111" },
    trOdd: TABLE_CLEAR_ROW,
    trEven: TABLE_CLEAR_ROW,
  },
  {
    id: "classic",
    label: "Classic Grid",
    colorMode: "none",
    table: { width: "100%", "border-collapse": "collapse", "font-size": "10px" },
    thead: { "background-color": "transparent", color: "#111111" },
    tfoot: { "background-color": "transparent", color: "#111111" },
    th: { padding: "6px 8px", "font-weight": "700", "font-size": "9px", "text-align": "left", border: "1px solid #dddddd", color: "#111111", "background-color": "transparent" },
    td: { padding: "6px 8px", border: "1px solid #dddddd", "background-color": "transparent", color: "#111111" },
    trOdd: TABLE_CLEAR_ROW,
    trEven: TABLE_CLEAR_ROW,
  },
  {
    id: "lined",
    label: "Horizontal Lines",
    colorMode: "none",
    table: { width: "100%", "border-collapse": "collapse", "font-size": "10px" },
    thead: { "background-color": "transparent", color: "#111111" },
    tfoot: { "background-color": "transparent", color: "#111111" },
    th: { padding: "6px 8px", "font-weight": "700", "font-size": "9px", "text-align": "left", border: "none", "border-bottom": "2px solid #111111", color: "#111111", "background-color": "transparent" },
    td: { padding: "6px 8px", border: "none", "border-bottom": "1px solid #e5e5e5", "background-color": "transparent", color: "#111111" },
    trOdd: TABLE_CLEAR_ROW,
    trEven: TABLE_CLEAR_ROW,
  },
  {
    id: "minimal",
    label: "Minimal",
    colorMode: "none",
    table: { width: "100%", "border-collapse": "collapse", "font-size": "10px" },
    thead: { "background-color": "transparent", color: "#6b7280" },
    tfoot: { "background-color": "transparent", color: "#111111" },
    th: { padding: "4px 6px", "font-weight": "600", "font-size": "8px", "text-align": "left", "text-transform": "uppercase", "letter-spacing": "0.04em", border: "none", "border-bottom": "1px solid #d1d5db", color: "#6b7280", "background-color": "transparent" },
    td: { padding: "5px 6px", border: "none", "background-color": "transparent", color: "#111111" },
    trOdd: TABLE_CLEAR_ROW,
    trEven: TABLE_CLEAR_ROW,
  },
  {
    id: "striped",
    label: "Zebra Rows",
    colorMode: "none",
    table: { width: "100%", "border-collapse": "collapse", "font-size": "10px" },
    thead: { "background-color": "transparent", color: "#111111" },
    tfoot: { "background-color": "transparent", color: "#111111" },
    th: { padding: "6px 8px", "font-weight": "700", "font-size": "9px", "text-align": "left", border: "none", "border-bottom": "1px solid #d1d5db", color: "#111111", "background-color": "transparent" },
    td: { padding: "6px 8px", border: "none", "background-color": "transparent", color: "#111111" },
    trOdd: { "background-color": "#ffffff" },
    trEven: { "background-color": "#f3f4f6" },
  },
  {
    id: "outlined",
    label: "Outlined",
    colorMode: "none",
    table: {
      width: "100%",
      "border-collapse": "separate",
      "border-spacing": "0",
      "font-size": "10px",
      border: "2px solid #333333",
      overflow: "visible",
      "border-radius": "0",
    },
    thead: { "background-color": "transparent", color: "#111111" },
    tfoot: { "background-color": "transparent", color: "#111111" },
    th: { padding: "6px 8px", "font-weight": "700", "font-size": "9px", "text-align": "left", border: "1px solid #333333", color: "#111111", "background-color": "transparent" },
    td: { padding: "6px 8px", border: "1px solid #333333", "background-color": "transparent", color: "#111111" },
    trOdd: TABLE_CLEAR_ROW,
    trEven: TABLE_CLEAR_ROW,
  },
  {
    id: "columns",
    label: "Column Lines",
    colorMode: "none",
    table: { width: "100%", "border-collapse": "collapse", "font-size": "10px" },
    thead: { "background-color": "transparent", color: "#111111" },
    tfoot: { "background-color": "transparent", color: "#111111" },
    th: { padding: "6px 10px", "font-weight": "700", "font-size": "9px", "text-align": "left", border: "none", "border-right": "1px solid #d1d5db", color: "#111111", "background-color": "transparent" },
    td: { padding: "6px 10px", border: "none", "border-right": "1px solid #e5e7eb", "background-color": "transparent", color: "#111111" },
    trOdd: TABLE_CLEAR_ROW,
    trEven: TABLE_CLEAR_ROW,
  },
  {
    id: "boxed",
    label: "Boxed Cells",
    colorMode: "none",
    table: {
      width: "100%",
      "border-collapse": "separate",
      "border-spacing": "4px",
      "font-size": "10px",
      border: "none",
    },
    thead: { "background-color": "transparent", color: "#111111" },
    tfoot: { "background-color": "transparent", color: "#111111" },
    th: { padding: "6px 8px", "font-weight": "700", "font-size": "9px", "text-align": "left", border: "1px solid #e5e7eb", "border-radius": "4px", color: "#111111", "background-color": "transparent" },
    td: { padding: "6px 8px", border: "1px solid #e5e7eb", "border-radius": "4px", "background-color": "transparent", color: "#111111" },
    trOdd: TABLE_CLEAR_ROW,
    trEven: TABLE_CLEAR_ROW,
  },
  {
    id: "compact",
    label: "Compact",
    colorMode: "none",
    table: { width: "100%", "border-collapse": "collapse", "font-size": "9px" },
    thead: { "background-color": "transparent", color: "#111111" },
    tfoot: { "background-color": "transparent", color: "#111111" },
    th: { padding: "3px 5px", "font-weight": "700", "font-size": "8px", "text-align": "left", border: "1px solid #e5e7eb", color: "#111111", "background-color": "transparent" },
    td: { padding: "3px 5px", border: "1px solid #e5e7eb", "background-color": "transparent", color: "#111111" },
    trOdd: TABLE_CLEAR_ROW,
    trEven: TABLE_CLEAR_ROW,
  },
  {
    id: "spaced",
    label: "Spacious",
    colorMode: "none",
    table: { width: "100%", "border-collapse": "collapse", "font-size": "10px" },
    thead: { "background-color": "transparent", color: "#111111" },
    tfoot: { "background-color": "transparent", color: "#111111" },
    th: { padding: "10px 12px", "font-weight": "700", "font-size": "9px", "text-align": "left", border: "none", "border-bottom": "1px solid #e5e7eb", color: "#111111", "background-color": "transparent" },
    td: { padding: "10px 12px", border: "none", "border-bottom": "1px solid #f3f4f6", "background-color": "transparent", color: "#111111" },
    trOdd: TABLE_CLEAR_ROW,
    trEven: TABLE_CLEAR_ROW,
  },
  {
    id: "dotted",
    label: "Dotted",
    colorMode: "none",
    table: { width: "100%", "border-collapse": "collapse", "font-size": "10px" },
    thead: { "background-color": "transparent", color: "#111111" },
    tfoot: { "background-color": "transparent", color: "#111111" },
    th: { padding: "6px 8px", "font-weight": "700", "font-size": "9px", "text-align": "left", border: "1px dotted #bdbdbd", color: "#111111", "background-color": "transparent" },
    td: { padding: "6px 8px", border: "1px dotted #d1d5db", "background-color": "transparent", color: "#111111" },
    trOdd: TABLE_CLEAR_ROW,
    trEven: TABLE_CLEAR_ROW,
  },
  {
    id: "double-rule",
    label: "Double Rule",
    colorMode: "none",
    table: { width: "100%", "border-collapse": "collapse", "font-size": "10px", "border-top": "3px double #111111", "border-bottom": "3px double #111111" },
    thead: { "background-color": "transparent", color: "#111111" },
    tfoot: { "background-color": "transparent", color: "#111111" },
    th: { padding: "6px 8px", "font-weight": "700", "font-size": "9px", "text-align": "left", border: "none", "border-bottom": "1px solid #111111", color: "#111111", "background-color": "transparent" },
    td: { padding: "6px 8px", border: "none", "background-color": "transparent", color: "#111111" },
    trOdd: TABLE_CLEAR_ROW,
    trEven: TABLE_CLEAR_ROW,
  },
  {
    id: "accent-header",
    label: "Accent Header",
    colorMode: "accent",
    table: { width: "100%", "border-collapse": "collapse", "font-size": "10px" },
    thead: { "background-color": "#111111", color: "#ffffff" },
    tfoot: { "background-color": "#111111", color: "#ffffff" },
    th: { padding: "6px 8px", "font-weight": "700", "font-size": "9px", "text-align": "left", border: "none", color: "#ffffff", "background-color": "transparent" },
    td: { padding: "6px 8px", border: "none", "border-bottom": "1px solid #e5e7eb", "background-color": "transparent", color: "#111111" },
    trOdd: TABLE_CLEAR_ROW,
    trEven: { "background-color": "#f9fafb" },
  },
];

export function tableTemplateWithColor(baseId, color) {
  const base = TABLE_STYLE_TEMPLATES.find((t) => t.id === baseId) || TABLE_STYLE_TEMPLATES[0];

  if (base.colorMode === "none") {
    return {
      ...base,
      id: `${base.id}-${color.replace("#", "")}`,
      thead: { ...base.thead, "background-color": "transparent", color },
      tfoot: { ...base.tfoot, "background-color": "transparent", color },
      th: {
        ...base.th,
        color,
        "background-color": "transparent",
        "border-bottom-color": color,
        "border-color": color,
      },
      td: { ...base.td, "background-color": "transparent" },
      trOdd: TABLE_CLEAR_ROW,
      trEven: base.trEven?.["background-color"] && base.trEven["background-color"] !== "transparent"
        ? base.trEven
        : TABLE_CLEAR_ROW,
    };
  }

  return {
    ...base,
    id: `${base.id}-${color.replace("#", "")}`,
    thead: { ...base.thead, "background-color": color, color: "#ffffff" },
    tfoot: { ...base.tfoot, "background-color": color, color: "#ffffff" },
    th: { ...base.th, color: "#ffffff", "border-color": color, "background-color": "transparent" },
  };
}
